### ISSUE TITLE
yuzu-room always runs with a password

### ISSUE THREAD

**Issue by mctaylors** [K4rian/docker-yuzu-room#2]
Using Docker Compose

When I start my container, even when I set `YUZU_PASSWORD=""` or commented it out, my yuzu-room will still require a password.

**Comment by K4rian** [comment]
Hey,

Beside the environment variable, did you remove (or comment) the secret definition from the compose file before starting the server?

Everything is working as intended on my side:
![yuzu_Jm484snYzR](https://github.com/K4rian/docker-yuzu-room/assets/41601236/85e42f94-d575-436a-8430-e6122325ea85)
_(click to enlarge)_

Not sure what's causing your issue.

**Comment by makuraslvt** [comment]
> did you remove (or comment) the secret definition from the compose file before starting the server?
Yes, I actually did, I can try to show the issue with a video clip.

UPD: hold up, maybe I misunderstood something...

**Comment by mctaylors** [comment]
[](https://github.com/K4rian/docker-yuzu-room/assets/95250141/6ee3b26b-237c-4c45-b56e-d1a95ba2c34c)

**Comment by makuraslvt** [comment]
> UPD: hold up, maybe I misunderstood something...

So, I've commented out only variable in `yuzu-room.env` actually, and that's the reason why it didn't worked. Thank you for helping!

**Comment by K4rian** [comment]
For a quick passwordless room set-up, you can omit the `.env` file and use the environment variables inline:

```yaml
services:
  yuzu-room:
    image: k4rian/yuzu-room:latest
    container_name: yuzu-room
    volumes:
      - data:/home/yuzu
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Required
      - YUZU_BINDADDR="0.0.0.0"
      - YUZU_PORT=24872
      - YUZU_ROOMNAME="yuzu Room"
      - YUZU_PREFGAME="Any"
      - YUZU_MAXMEMBERS=4
      # Optional
      - YUZU_ROOMDESC=""
      - YUZU_PREFGAMEID="0"
    ports:
      - 24872:24872/tcp
      - 24872:24872/udp
    ulimits:
      memlock: -1
    restart: unless-stopped

volumes:
  data:
```

_Note:_ Servers can't be registered as public via the yuzu API anymore since the entire project has been shutting down. I'll update the Docker file and images ASAP to reflect the changes.

Thanks for your interest in the project, have fun!
