### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by sehraf** [K4rian/docker-yuzu-room#4]
System: Arch ARM 64bit

When using `docker-compose` the container fails creation:
```
> docker-compose up -d yuzu-room
[+] Running 1/2
 ✔ Network management_default  Created                                                                                                                                                                                                                                                                                   0.2s 
 ⠸ Container yuzu-room         Starting                                                                                                                                                                                                                                                                                  1.2s 
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./docker-entrypoint.sh": stat ./docker-entrypoint.sh: no such file or directory: unknown
```

Docker compose entry:
```yaml
  yuzu-room:
    image: k4rian/yuzu-room:latest
    container_name: yuzu-room
    restart: unless-stopped
    volumes:
      - ./volumes/yuzu-room:/home/yuzu
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - yuzu-room.env
    # secrets:
    #   - yuzuroom
    ports:
      - 24872:24872/tcp
      - 24872:24872/udp
    ulimits:
      memlock: -1
```

**Comment by K4rian** [comment]
Hi,

I tried running the ARM64 Docker container using QEMU and encountered the same "segmentation fault" error you mentioned in your [previous post](https://github.com/K4rian/docker-yuzu-room/issues/3#issuecomment-2284355199). You were right. 

Unfortunately, the core dump also seems corrupted when analyzed with gdb. Unfortunately, I don't have time to recompile the server with debug symbols and do a more in-depth check using gdb.

I'm afraid that until someone can take a closer look, the ARM build is borked for now. Sorry about that.

Thank you for your report.

**Comment by K4rian** [comment]
After a brief investigation, I was able to resolve the issue with the ARM64 image (see commit 4d3ab04). 
Since I don't have access to an ARM device, I've only tested it in a virtual machine. 

Could you please run the following commands to verify if everything works as expected?

```bash
docker pull k4rian/yuzu-room
```
```bash
printf "Q\n" | docker run --rm --name yuzu-room-test -i k4rian/yuzu-room
```

Thanks.

**Comment by sehraf** [comment]
Works as expected, thanks for the quick response!

I've also found the cause for
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./docker-entrypoint.sh": stat ./docker-entrypoint.sh: no such file or directory: unknown`

the volume via local folder was the culprit
```
    volumes:
      - ./volumes/yuzu-room:/home/yuzu
```
Don't ask my why :shrug: Also doesn't really matter, so I've just removed the entry.

**Comment by K4rian** [comment]
Glad to hear it worked. Thanks for your feedback.

When you mount a local folder using `-v`, the contents of the corresponding directory inside the container are replaced by the contents of the local folder on your host machine. 

So if `./volumes/yuzu-room` is empty, the `/home/yuzu` directory within the container will also be empty, which explains why `./docker-entrypoint.sh` couldn't be found.

If you really want to use a volume, you can consider the following approaches:

* Mount specific files instead of the entire root directory:
```yaml
...
- ./volumes/yuzu-room/yuzu-room.log:/home/yuzu/yuzu-room.log
- ./volumes/yuzu-room/bannedlist.ybl:/home/yuzu/bannedlist.ybl
...
```

* Use a Docker volume:
```yaml
services:
  yuzu-room:
    image: k4rian/yuzu-room:latest
    container_name: yuzu-room
    hostname: yuzu-room
    volumes:
      - data:/home/yuzu
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - yuzu-room.env
    ports:
      - 24872:24872/tcp
      - 24872:24872/udp
    restart: unless-stopped

volumes:
  data:
```

* Run a test container to populate `./volumes/yuzu-room` with the server files:
```bash
docker run \
  --rm \
  --entrypoint /bin/sh \
  -v ./volumes/yuzu-room:/mountpoint \
  k4rian/yuzu-room \
  -c "cp -R /home/yuzu/. /mountpoint"
```

`./volumes/yuzu-room` should now contain all the necessary files, including the entrypoint script:
```bash
ls -l ./volumes/yuzu-room
```
Your original Compose file should work as expected.

Feel free to experiment and see what works best for you.
